/** Standard medical specialties for doctor profile forms. */
export const DOCTOR_SPECIALTY_OPTIONS = [
  'Allergy & Immunology',
  'Anesthesiology',
  'Bariatric Surgery',
  'Cardiology',
  'Cardiothoracic Surgery',
  'Chiropractic Care',
  'Clinical Genetics',
  'Dermatology',
  'Emergency Medicine',
  'Endocrinology',
  'Family Medicine',
  'Gastroenterology',
  'General Medicine',
  'General Surgery',
  'Geriatric Medicine',
  'Gynecology',
  'Hematology',
  'Hepatology',
  'Infectious Disease',
  'Internal Medicine',
  'Nephrology',
  'Neurology',
  'Neurosurgery',
  'Nuclear Medicine',
  'Obstetrics (OB)',
  'Obstetrics & Gynecology (OB/GYN)',
  'Oncology',
  'Ophthalmology',
  'Oral & Maxillofacial Surgery',
  'Orthopedic Surgery',
  'Otolaryngology (ENT)',
  'Pain Management',
  'Palliative Care',
  'Pathology',
  'Pediatrics',
  'Pediatric Cardiology',
  'Pediatric Neurology',
  'Pediatric Surgery',
  'Physical Medicine & Rehabilitation',
  'Plastic Surgery',
  'Podiatry',
  'Psychiatry',
  'Psychology',
  'Pulmonology',
  'Radiation Oncology',
  'Radiology',
  'Rheumatology',
  'Sleep Medicine',
  'Sports Medicine',
  'Urology',
  'Vascular Surgery'
] as const;
