-- Consultation invoice PDF (generated by PSE before payment link is sent)

alter table public.opinion_requests
  add column if not exists invoice_pdf_storage_path text,
  add column if not exists invoice_generated_at timestamptz,
  add column if not exists invoice_number text,
  add column if not exists invoice_subtotal numeric,
  add column if not exists invoice_tax_rate numeric,
  add column if not exists invoice_tax_amount numeric,
  add column if not exists invoice_total numeric;

create index if not exists opinion_requests_invoice_generated_at_idx
  on public.opinion_requests (invoice_generated_at)
  where invoice_pdf_storage_path is not null;
